name : Build and Push ECR to AWS 
on:
  workflow_dispatch

jobs:
  working-job:
    runs-on: ubuntu-latest

    steps:
      - name : Echo Message
        run : echo "Build and Push ECR to AWS is working successfully ✅"