name: Main Pipeline for Orchestrate

on:
  push:
    branches:
      - main
  workflow_dispatch:

  jobs:
    verify_connection:
      uses: ./.github/workflows/test_connection.yml
      permissions:
        id-token: write
        contents: read

test_fleet_health_envs:
   needs: verify_connection
   uses: ./.github/workflows/test_fleet_health.yml
   permissions:
     id-token: write
     contents: read