name: Test Connection

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test Connection
        run: echo "Connection successful ✅"